"""
This script is responsible for the 'Data Transformation' phase of the machine learning 
pipeline. Its main job is to take the raw training and testing data generated by the 
Data Ingestion component and clean/format it so that a machine learning model can 
understand it. This includes handling missing values, scaling numerical features so 
they are on the same scale, and encoding categorical text data into numbers (One-Hot Encoding). 
Finally, it saves this entire transformation process as a 'pickle' (.pkl) file so that 
new, incoming data in the future can be transformed using the exact same rules.
"""

import sys
from dataclasses import dataclass
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from src.exception import CustomException
from src.logger import logging
import os
from src.utils import save_object


@dataclass
class DataTransformationConfig:
    # This configures the path where our trained preprocessor object will be saved.
    # It will create a file named 'preprocessor.pkl' inside the 'artifacts' folder.
    preprocessor_obj_file_path = os.path.join('artifacts', "preprocessor.pkl")


class DataTransformation:
    def __init__(self):
        # Automatically load the configuration paths when the class is initialized.
        self.data_transformation_config = DataTransformationConfig()

    def get_data_transformer_object(self):
        '''
        This function is responsible for building the actual data transformation pipeline.
        It defines exactly how numerical and categorical columns should be processed.
        '''
        try:
            # Step 1: Define which columns are numbers and which are text/categories.
            numerical_columns = ["writing_score", "reading_score"]
            categorical_columns = [
                "gender",
                "race_ethnicity",
                "parental_level_of_education",
                "lunch",
                "test_preparation_course",
            ]

            # Step 2: Create a pipeline for numerical data
            num_pipeline = Pipeline(
                steps=[
                # Imputer fills in missing values. 'median' is chosen as it's robust to outliers.
                ("imputer", SimpleImputer(strategy="median")),  
                
                # Scaler standardizes the numbers so they have a mean of 0 and variance of 1.
                ("scaler", StandardScaler())
                ]
            )    

            # Step 3: Create a pipeline for categorical data
            cat_pipeline = Pipeline(
                steps=[
                # Fills missing text values with the most frequent value (the mode).
                ("imputer", SimpleImputer(strategy="most_frequent")),
                
                # Converts categories into numerical columns (e.g., gender_male: 1 or 0).
                ("one_hot_encoder", OneHotEncoder()),
                
                # Scales the newly created one-hot encoded columns.
                # with_mean=False is used because OneHotEncoder outputs a sparse matrix.
                ("scaler", StandardScaler(with_mean=False))
                ]
            )

            logging.info("Categorical columns encoding completed")
            logging.info("Numerical columns scaling completed")

            # Step 4: Combine both pipelines into a single ColumnTransformer.
            # This tells Scikit-Learn: "Apply the num_pipeline to numerical_columns, 
            # and apply the cat_pipeline to categorical_columns."
            preprocessor = ColumnTransformer(
                [
                    ("num_pipeline", num_pipeline, numerical_columns),
                    ("cat_pipeline", cat_pipeline, categorical_columns)
                ]
            )
            
            # Return the un-trained pipeline object to be used later
            return preprocessor
        
        except Exception as e:
            # Catch and log any errors using our custom exception handler
            raise CustomException(e, sys)


    def initiate_data_transformation(self, train_path, test_path):
        """
        This function takes the paths of the train and test data, applies the 
        transformation rules, and saves the preprocessor object.
        """
        try:
            # Step 1: Read the train and test data (paths provided by Data Ingestion)
            train_df = pd.read_csv(train_path)
            test_df = pd.read_csv(test_path)
            
            logging.info("Read train and test data completed") 
            logging.info("Obtaining preprocessing object")

            # Get the fully constructed pipeline from the function above
            preprocessing_obj = self.get_data_transformer_object()
            
            # Identify the target column we want our model to predict
            target_column_name = "math_score"
            numerical_columns = ["writing_score", "reading_score"]   

            # Step 2: Separate the input features (X) from the target feature (y) for TRAINING data
            input_feature_train_df = train_df.drop(columns=[target_column_name])
            target_feature_train_df = train_df[target_column_name]

            # Separate the input features (X) from the target feature (y) for TESTING data
            input_feature_test_df = test_df.drop(columns=[target_column_name])
            target_feature_test_df = test_df[target_column_name]

            logging.info(
                f"Applying preprocessing object on training dataframe and testing dataframe."
            )

            # Step 3: Apply the transformations!
            # fit_transform() learns the parameters (like median and standard deviation) 
            # from the training data AND applies them.
            input_feature_train_arr = preprocessing_obj.fit_transform(input_feature_train_df)
            
            # transform() ONLY applies the learned parameters from the training data 
            # to the testing data. This prevents 'data leakage'.
            input_feature_test_arr = preprocessing_obj.transform(input_feature_test_df)

            # Step 4: Re-combine the transformed inputs (X) with their target values (y).
            # np.c_ is a numpy shorthand that concatenates the arrays side-by-side (column-wise).
            train_arr = np.c_[
                input_feature_train_arr, np.array(target_feature_train_df)
            ]
            test_arr = np.c_[input_feature_test_arr, np.array(target_feature_test_df)]

            logging.info(f"Saved preprocessing object.")

            # Step 5: Save the fully trained preprocessor object as a physical file.
            # We use a custom utility function 'save_object' (which uses the 'pickle' library).
            save_object(
                file_path=self.data_transformation_config.preprocessor_obj_file_path,
                obj=preprocessing_obj
            )

            # Return the transformed arrays and the path to the saved preprocessor pickle file.
            # The next component (Model Trainer) will catch these values.
            return (
                train_arr,
                test_arr,
                self.data_transformation_config.preprocessor_obj_file_path,
            )
            
        except Exception as e:
            raise CustomException(e, sys)